version: '3.8'

services:
  # PostgreSQL
  db:
    image: postgres:15
    environment:
      TZ: Europe/Moscow 
      POSTGRES_USER: myapp_user
      POSTGRES_PASSWORD: secure_password
      POSTGRES_DB: myapp_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    networks:
      - app-network

  backend:
    build: ./backend
    restart: unless-stopped  # Автоматически перезапускается при падении
    depends_on:
      - db
    environment:
      TZ: Europe/Moscow 
      JWT_SECRET: your_very_strong_secret_here
      DB_HOST: db
      DB_USER: myapp_user
      DB_PASSWORD: secure_password
      DB_NAME: myapp_db
    ports:
      - "3000:3000"
    networks:
      - app-network

  # Nginx (фронтенд + прокси к бэкенду)
  nginx:
    image: nginx:alpine
    depends_on:
      - backend
    volumes:
      - ./frontend:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge


    