version: '3.8'

services:
  backend:
    build: ./backend
    restart: unless-stopped
    environment:
      TZ: Europe/Moscow 
      NODE_ENV: production
      JWT_SECRET: your_very_strong_secret_here
      DB_HOST: 6efc77aa9da03edbf209d4a0.twc1.net  # Домен из вашего скриншота
      DB_PORT: 5432
      DB_USER: gen_user
      DB_PASSWORD: YZ>|^DuMF+P7LX  # Ваш настоящий пароль
      DB_NAME: default_db
      DB_SSL: true
    ports:
      - "3000:3000"
    networks:
      - app-network

  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    depends_on:
      - backend
    ports:
      - "80:80"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge