version: '3.8'

services:
  # Backend приложение
  backend:
    build: 
      context: ./backend
    restart: unless-stopped
    environment:
      TZ: Europe/Moscow 
      NODE_ENV: production
      JWT_SECRET: your_very_strong_secret_here
      DB_HOST: 192.168.0.4  # Публичный IP из вашего скрина
      DB_PORT: 5432
      DB_USER: gen_user       # Пользователь из скрина
      DB_PASSWORD: YZ>|^DuMF+P7LX  # Замените на реальный пароль
      DB_NAME: default_db     # База данных из скрина
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Nginx с кастомным образом
  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    depends_on:
      backend:
        condition: service_healthy
    ports:
      - "80:80"
    networks:
      - app-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  app-network:
    driver: bridge