version: '3.8'

services:
  backend:
    build: .              # Dockerfile в корне
    environment:
      NODE_ENV: production
      DB_HOST: 176.53.160.66
      DB_PORT: 5432
      DB_USER: gen_user
      DB_PASSWORD: YZ>|^DuMF+P7LX
      DB_NAME: default_db
      DB_SSL: "false"
