version: '3.8'

services:
  backend:
    build: ./backend
    restart: unless-stopped
    environment:
      NODE_ENV: production
      JWT_SECRET: your_very_strong_secret_here
      DB_HOST: 6efc77aa9da03edbf209d4a0.twc1.net
      DB_PORT: 5432
      DB_USER: gen_user
      DB_PASSWORD: YZ>|^DuMF+P7LX
      DB_NAME: default_db
      DB_SSL: "true"
    ports:
      - "80:3000"  # Прямое пробрасывание порта