version: '3.8'

services:
  # PostgreSQL (без тома)
  db:
    image: postgres:15
    environment:
      TZ: Europe/Moscow 
      POSTGRES_USER: myapp_user
      POSTGRES_PASSWORD: secure_password
      POSTGRES_DB: myapp_db
    # Убрано: volumes
    networks:
      - app-network
    restart: unless-stopped

  # Backend приложение
  backend:
    build: 
      context: ./backend
    restart: unless-stopped
    depends_on:
      - db
    environment:
      TZ: Europe/Moscow 
      NODE_ENV: production
      JWT_SECRET: your_very_strong_secret_here
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: myapp_user
      DB_PASSWORD: secure_password
      DB_NAME: myapp_db
    networks:
      - app-network

  # Nginx с кастомным образом (без томов)
  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    depends_on:
      - backend
    ports:
      - "80:80"
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge