version: '3.8'

services:
  # PostgreSQL
  db:
    image: postgres:15
    environment:
      TZ: Europe/Moscow 
      POSTGRES_USER: myapp_user
      POSTGRES_PASSWORD: secure_password
      POSTGRES_DB: myapp_db
    # Убрали volumes
    ports:
      - "5432:5432"
    networks:
      - app-network

  backend:
    build: ./backend
    restart: unless-stopped
    depends_on:
      - db
    environment:
      TZ: Europe/Moscow 
      JWT_SECRET: your_very_strong_secret_here
      DB_HOST: db
      DB_USER: myapp_user
      DB_PASSWORD: secure_password
      DB_NAME: myapp_db
    ports:
      - "3000:3000"
    networks:
      - app-network

  # Nginx (фронтенд + прокси к бэкенду)
  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    depends_on:
      - backend
    # Убрали volumes
    ports:
      - "80:80"
    networks:
      - app-network

# Убрали секцию volumes

networks:
  app-network:
    driver: bridge